#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "IoT-Cloud-LED-Thing"
  https://create.arduino.cc/cloud/things/a4f90ddf-fb5c-4212-bff3-8502874896ed

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  bool light;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define LED_PIN 2

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  //Initialize project
  pinMode(LED_PIN, OUTPUT);
}

void loop() {
  ArduinoCloud.update();
  // Your code here


}


void onLightChange() {
  // Do something
  digitalWrite(LED_PIN, light);
  Serial.print("The light is ");
  if (light) {
    Serial.println("ON");
  } else {
    Serial.println("OFF");
  }
}



